### ISSUE TITLE
Atributo alt en las imágenes

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/c-s1-lamarr-de-salas#2]
En general, cada `<img>` debería llevar un atributo `alt=""` donde se hace una descripción literal de la imagen (y es el texto que aparecerá en lugar de la imagen en el caso en que esta no se pueda cargar).

Hay casos en los que se puede añadir el atributo alt vacío como en el caso de las imágenes que son puramente decorativas, pero también, este tipo de imágenes deberían meterse por css.

En cualquier caso, revisad el código y colocad los alt apropiados ;)

**Comment by mluena** [comment]
Pregunta, no me queda claro eso de q ese tipo de imágenes hay q meterlas por CSS. Si yo meto una imagen con su etiqueta y su atributo alt correspondiente en el HTML, en el CSS le pongo las propiedades que necesite pero nada relacionado con alt, no?

**Comment by oneeyedman** [comment]
🙀  Este sigue tb pendiente!

**Comment by oneeyedman** [comment]
Lo he cerrado sin querer :(

**Comment by oneeyedman** [comment]
Sweet!
