### ISSUE TITLE
HR con atributo class mal aplicado

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/c-s1-lamarr-de-salas#4]
Echad un ojo porque hay un `<hr line-section-2>` con la clase aplicada a pecho palomo. Por supuesto que es un error, igualmente, echadle un ojo y poned la clase firme.

**Comment by gala1234** [comment]
Siii lo corregí, pero ahora no me va el git y no puedo ni subir ni bajar nada.. pensaba peguntar el lunes como arreglarlo:

![image](https://user-images.githubusercontent.com/33252067/32698356-b66a5af2-c7a4-11e7-83c0-a806b32f23ba.png)

**Comment by guerrero** [comment]
Hola @gala1234, prueba a ejecutar `xcode-select --install` desde la Terminal y después vuelve a ejecutar `git status` de nuevo.

Al ejecutar `xcode-select --install` probablemente te pregunte si quieres instalar las herramientas de línea de comandos, debes darle a aceptar.

**Comment by gala1234** [comment]
Gracias  @guerrero !! lo pregunte por slack y Carlos me dijo lo mismo y me funcionó, muchas Gracias 👍

**Comment by oneeyedman** [comment]
Nice!
